# -*- coding: utf-8 -*-
"""SWOT_PIXC_D_lakes_pipelin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkatKvXNXRl-CEmUPZtZYHZA_IyW8nga

# SWOT PIXC Version D — Lake Water Level Pipeline

**Product:** `SWOT_L2_HR_PIXC_D` — Level 2 Water Mask Pixel Cloud, Version D  
**Lake bounding box:** `(12.542019, 42.517160, 12.558057, 42.523060)` — `(lon_min, lat_min, lon_max, lat_max)`  
**Clip shapefile:** user-supplied lake mask  
**Output:** per-acquisition median and mean water surface elevation (WSE) in metres  

---
### What is PIXC?
Unlike the gridded Raster product, PIXC delivers an **unstructured point cloud**: each water pixel is an independent observation with its own `latitude`, `longitude`, and `height` (ellipsoidal WSE in metres, WGS84).  
The workflow here is therefore:
1. Download the PIXC NetCDF granule
2. Load pixel arrays (`latitude`, `longitude`, `height`, `classification`, `cross_track`)
3. Filter to **water pixels** inside the **lake shapefile**
4. Compute mean & median WSE over retained pixels

> **Run in Google Colab with Google Drive mounted.**

## 1. Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install earthaccess geopandas shapely netCDF4 numpy pandas tqdm matplotlib

"""## 2. Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""## 3. Configuration"""

# ── USER SETTINGS ─────────────────────────────────────────────────────────────

# Bounding box: (lon_min, lat_min, lon_max, lat_max)  [WGS84 degrees]
LAKE_BBOX = (12.542019, 42.517160, 12.558057, 42.523060)

# Date range for SWOT acquisitions
DATE_START = "2024-11-01"   # ← change as needed
DATE_END   = "2025-02-28"   # ← change as needed

# Shapefile used to spatially filter pixels
SHAPEFILE_PATH = (
    "/path/Recentino/"
    "mask.shp"
)

# SWOT Pixel Cloud Version D — NASA short name & collection concept ID
SWOT_SHORT_NAME      = "SWOT_L2_HR_PIXC_D"
SWOT_COLLECTION_ID   = "C3233944986-POCLOUD"   # used as a fallback if short_name search fails

# PIXC NetCDF group and variable names
# All water-pixel data live in the '/pixel_cloud' group
PIXC_GROUP          = "pixel_cloud"
LAT_VAR             = "latitude"          # degrees_north
LON_VAR             = "longitude"         # degrees_east
HEIGHT_VAR          = "height"            # metres above WGS84 ellipsoid
CLASS_VAR           = "classification"    # 3 = open water, 4 = dark water
WATER_CLASS_VALUES  = [3, 4]              # pixel classes considered open water

# Optional: filter by cross_track distance to remove near-nadir artifacts
# Set to None to keep all pixels
MIN_CROSS_TRACK_M   = None   # metres  (None to disable)
MAX_CROSS_TRACK_M   = None     # metres  (None to disable)

# Output CSV path
OUTPUT_CSV = (
    "/path/Recentino /"
    "lake_wse_statistics_PIXC_D.csv"
)

# ──────────────────────────────────────────────────────────────────────────────
print("Configuration loaded.")
print(f"  Product    : {SWOT_SHORT_NAME}")
print(f"  BBOX       : {LAKE_BBOX}")
print(f"  Date range : {DATE_START}  →  {DATE_END}")
print(f"  Shapefile  : {SHAPEFILE_PATH}")

"""## 4. Authenticate with NASA Earthdata"""

import earthaccess

# Opens browser / credential prompt first time; cached in ~/.netrc afterwards.
auth = earthaccess.login(strategy="interactive", persist=True)
print("Authenticated:", auth.authenticated)

"""## 5. Search SWOT PIXC Granules"""

lon_min, lat_min, lon_max, lat_max = LAKE_BBOX

results = earthaccess.search_data(
    short_name   = SWOT_SHORT_NAME,
    temporal     = (DATE_START, DATE_END),
    bounding_box = (lon_min, lat_min, lon_max, lat_max),
)

print(f"Found {len(results)} granule(s).")
for g in results[:20]:
    try:
        dt = g['umm']['TemporalExtent']['RangeDateTime']['BeginningDateTime']
    except Exception:
        dt = "unknown"
    print(f"  • {dt[:19]}  {g['umm']['GranuleUR']}")

"""## 6. Load the Lake Shapefile"""

import geopandas as gpd

lake_gdf = gpd.read_file(SHAPEFILE_PATH).to_crs(epsg=4326)  # ensure WGS84
lake_union = lake_gdf.unary_union   # single geometry for point-in-polygon tests

print(f"CRS after reprojection : {lake_gdf.crs}")
print(f"Number of features     : {len(lake_gdf)}")
print(f"Bounds (WGS84)         : {lake_gdf.total_bounds}")
lake_gdf.plot(figsize=(5, 4), edgecolor='black', facecolor='lightblue')
import matplotlib.pyplot as plt
plt.title("Lake Mask Shapefile")
plt.tight_layout()
plt.show()

"""## 7. Helper Functions"""

import netCDF4 as nc
import numpy as np
import pandas as pd
from shapely.geometry import Point
import warnings
warnings.filterwarnings("ignore")


def get_granule_datetime(granule) -> str:
    """Extract the start datetime string from a granule metadata dict."""
    try:
        return granule['umm']['TemporalExtent']['RangeDateTime']['BeginningDateTime']
    except KeyError:
        return "unknown"




def filter_pixels_to_shapefile(df: pd.DataFrame, polygon) -> pd.DataFrame:
    """
    Keep only pixels whose (lon, lat) falls inside `polygon` (shapely geometry).
    Uses a fast bounding-box pre-filter before the exact point-in-polygon test.
    """
    if df.empty:
        return df

    # Bounding-box pre-filter
    minx, miny, maxx, maxy = polygon.bounds
    df = df[
        (df["lon"] >= minx) & (df["lon"] <= maxx) &
        (df["lat"] >= miny) & (df["lat"] <= maxy)
    ].copy()

    if df.empty:
        return df

    # Exact point-in-polygon
    inside = df.apply(
        lambda row: polygon.contains(Point(row["lon"], row["lat"])), axis=1
    )
    return df[inside].copy().reset_index(drop=True)


def compute_stats(df: pd.DataFrame) -> dict:
    """Return mean, median, std WSE and pixel count."""
    if df.empty:
        return {"mean_wse_m": np.nan, "median_wse_m": np.nan,
                "std_wse_m": np.nan, "n_pixels": 0}
    h = df["height"].values
    return {
        "mean_wse_m"   : float(np.mean(h)),
        "median_wse_m" : float(np.median(h)),
        "std_wse_m"    : float(np.std(h)),
        "n_pixels"     : int(len(h)),
    }


print("Helper functions defined.")

"""## 8. Main Loop — Download, Filter, Compute Statistics"""

def read_pixc_water_pixels(nc_path: str) -> pd.DataFrame:
    with nc.Dataset(nc_path, 'r') as ds:
        grp = ds[PIXC_GROUP]

        lat   = np.ma.filled(grp[LAT_VAR][:],    fill_value=np.nan).astype(float)
        lon   = np.ma.filled(grp[LON_VAR][:],    fill_value=np.nan).astype(float)
        h     = np.ma.filled(grp[HEIGHT_VAR][:], fill_value=np.nan).astype(float)
        cls   = np.ma.filled(grp[CLASS_VAR][:],  fill_value=-1).astype(int)
        geoid = np.ma.filled(grp['geoid'][:],    fill_value=np.nan).astype(float)
        tide  = np.ma.filled(grp['solid_earth_tide'][:], fill_value=np.nan).astype(float)

        if MIN_CROSS_TRACK_M is not None or MAX_CROSS_TRACK_M is not None:
            ct = np.abs(np.ma.filled(grp['cross_track'][:], fill_value=np.nan).astype(float)) \
                 if 'cross_track' in grp.variables else None
        else:
            ct = None

    # Orthometric height: subtract geoid and solid earth tide
    h_ortho = h - geoid - tide

    df = pd.DataFrame({
        "lat": lat, "lon": lon,
        "height": h_ortho,          # corrected orthometric height (m above MSL)
        "height_ellipsoidal": h,    # original ellipsoidal height, kept for reference
        "geoid": geoid,
        "solid_earth_tide": tide,
        "classification": cls
    })
    if ct is not None:
        df["cross_track"] = ct

    df = df[df["classification"].isin(WATER_CLASS_VALUES)]
    if "cross_track" in df.columns:
        if MIN_CROSS_TRACK_M is not None:
            df = df[df["cross_track"] >= MIN_CROSS_TRACK_M]
        if MAX_CROSS_TRACK_M is not None:
            df = df[df["cross_track"] <= MAX_CROSS_TRACK_M]

    df = df[np.isfinite(df["height"])].copy()
    return df.reset_index(drop=True)


# ── Main loop ──────────────────────────────────────────────────────────────────
import tempfile
from tqdm.notebook import tqdm

records = []

for granule in tqdm(results, desc="Processing PIXC granules"):
    dt_str = get_granule_datetime(granule)

    try:
        with tempfile.TemporaryDirectory() as tmpdir:

            # 1. Download
            local_paths = earthaccess.download([granule], local_path=tmpdir)
            nc_files = [str(p) for p in local_paths if str(p).endswith(".nc")]

            if not nc_files:
                print(f"  [SKIP] No .nc file for {dt_str[:19]}")
                continue

            nc_path = nc_files[0]

            # 2. Read water pixels (now returns orthometric heights)
            df_pixels = read_pixc_water_pixels(nc_path)

            if df_pixels.empty:
                print(f"  [SKIP] No water pixels found in {dt_str[:19]}")
                records.append({"datetime": dt_str, "mean_wse_m": np.nan,
                                "median_wse_m": np.nan, "std_wse_m": np.nan,
                                "n_pixels": 0})
                continue

            # 3. Clip to lake shapefile
            df_lake = filter_pixels_to_shapefile(df_pixels, lake_union)

            # 4. Compute statistics
            stats = compute_stats(df_lake)

        records.append({"datetime": dt_str, **stats})
        status = "✓" if stats["n_pixels"] > 0 else "○ (no pixels in lake)"
        print(f"  {status} {dt_str[:19]}  "
              f"mean={stats['mean_wse_m']:.3f} m  "
              f"median={stats['median_wse_m']:.3f} m  "
              f"n={stats['n_pixels']}")

    except Exception as exc:
        print(f"  [ERROR] {dt_str[:19]} — {exc}")
        records.append({"datetime": dt_str, "mean_wse_m": np.nan,
                        "median_wse_m": np.nan, "std_wse_m": np.nan,
                        "n_pixels": 0, "error": str(exc)})

print(f"\nDone — processed {len(records)} granule(s).")
'''
The correction applied per pixel is:
h_orthometric = h_ellipsoidal - geoid - solid_earth_tide
'''

"""## 9. Build Results Table"""

df_results = pd.DataFrame(records)
df_results["datetime"] = pd.to_datetime(df_results["datetime"])
df_results = df_results.sort_values("datetime").reset_index(drop=True)

# Keep only passes with at least one valid lake pixel
df_valid = df_results[df_results["n_pixels"] > 0].copy()

display_cols = ["datetime", "mean_wse_m", "median_wse_m", "std_wse_m", "n_pixels"]
print(f"Passes with valid lake pixels: {len(df_valid)} / {len(df_results)}")
print()
print(df_valid[display_cols].to_string(index=False))

"""## 10. Export to CSV"""

df_valid[display_cols].to_csv(OUTPUT_CSV, index=False)
print(f"Results saved to:\n  {OUTPUT_CSV}")

"""## 11. Time-Series Plot"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

fig, ax = plt.subplots(figsize=(13, 4))

ax.fill_between(
    df_valid["datetime"],
    df_valid["mean_wse_m"] - df_valid["std_wse_m"],
    df_valid["mean_wse_m"] + df_valid["std_wse_m"],
    alpha=0.15, color="steelblue", label="± 1σ (mean)"
)
ax.plot(df_valid["datetime"], df_valid["mean_wse_m"],
        marker="o", lw=1.5, color="steelblue", label="Mean WSE")
ax.plot(df_valid["datetime"], df_valid["median_wse_m"],
        marker="s", lw=1.5, ls="--", color="tomato", label="Median WSE")

ax.set_xlabel("Date")
ax.set_ylabel("Water Surface Elevation (m, EGM2008)")
ax.set_title("SWOT PIXC Version D — Lake Water Level")
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
ax.xaxis.set_major_locator(mdates.AutoDateLocator())
plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
ax.legend()
ax.grid(alpha=0.3)
plt.tight_layout()

plot_path = OUTPUT_CSV.replace(".csv", "_timeseries.png")
plt.savefig(plot_path, dpi=150)
plt.show()
print(f"Plot saved to:\n  {plot_path}")

"""## 12. (Optional) Scatter Map of Lake Pixels — Single Granule Inspection"""

# Set GRANULE_INDEX to inspect any single granule visually.
GRANULE_INDEX = 0

with tempfile.TemporaryDirectory() as tmpdir:
    local_paths = earthaccess.download([results[GRANULE_INDEX]], local_path=tmpdir)
    nc_files = [str(p) for p in local_paths if str(p).endswith(".nc")]
    df_px  = read_pixc_water_pixels(str(nc_files[0]))
    df_lk  = filter_pixels_to_shapefile(df_px, lake_union)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# All water pixels in the tile (bbox extent)
sc0 = axes[0].scatter(df_px["lon"], df_px["lat"], c=df_px["height"],
                      cmap="Blues", s=1, vmin=df_px["height"].quantile(0.02),
                                          vmax=df_px["height"].quantile(0.98))
lake_gdf.boundary.plot(ax=axes[0], color="red", lw=1)
plt.colorbar(sc0, ax=axes[0], label="WSE (m)")
axes[0].set_title(f"All water pixels — {len(df_px)} pts")

# Pixels clipped to lake shapefile
if not df_lk.empty:
    sc1 = axes[1].scatter(df_lk["lon"], df_lk["lat"], c=df_lk["height"],
                          cmap="plasma", s=6)
    plt.colorbar(sc1, ax=axes[1], label="WSE (m)")
else:
    axes[1].text(0.5, 0.5, "No lake pixels", ha="center", va="center",
                 transform=axes[1].transAxes, fontsize=14)
lake_gdf.boundary.plot(ax=axes[1], color="red", lw=1)
axes[1].set_title(f"Lake pixels — {len(df_lk)} pts  |  "
                  f"median={np.median(df_lk['height']):.3f} m" if not df_lk.empty else "Lake pixels — 0")

dt_label = get_granule_datetime(results[GRANULE_INDEX])[:19]
plt.suptitle(f"SWOT PIXC Version D  —  {dt_label}")
plt.tight_layout()
plt.show()
